In [7]:
# dependencies
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

In [10]:
#importing file path
#file path = "Bicycle_and_Pedestrian_Counts_in_Colorado (1).csv"
bike_data_to_load = Path("Bicycle_and_Pedestrian_Counts_in_Colorado (1).csv")

In [11]:
#store as a dataframe
bike_data_to_load = pd.read_csv(bike_data_to_load)
bike_data_to_load.head()

,stationId,dataCollected,county,location,lat,long,direction,month,year,dataDate,...,hr16,hr17,hr18,hr19,hr20,hr21,hr22,hr23,Location 1,Counties
0,B9012B,BIKE,Pueblo,"Memorial Dr, Lamar, CO",38.071995,-102.615190,South,5,2014,05/18/2014 12:00:00 AM,...,2,2,0,0,0,0,0,0,"(38.071995, -102.61519)",1064.0
1,B9012B,BIKE,Pueblo,"Memorial Dr, Lamar, CO",38.071995,-102.615190,North,10,2013,10/28/2013 12:00:00 AM,...,1,2,0,0,0,0,0,0,"(38.071995, -102.61519)",1064.0
2,B00050,BIKE & PEDESTRIAN,Weld,Greeley (Pouder River Trail at SH 257),40.444467,-104.883688,North,10,2012,10/25/2012 12:00:00 AM,...,1,1,0,0,0,0,0,0,"(40.4444673, -104.883688)",1072.0
3,B00049,BIKE & PEDESTRIAN,Adams,SOUTH PLATTE RIVER AT 74TH/YORK,39.826853,-104.949692,South,9,2012,09/29/2012 12:00:00 AM,...,17,14,4,0,3,1,0,0,"(39.82685334, -104.949692)",82.0
4,B00049,BIKE & PEDESTRIAN,Adams,SOUTH PLATTE RIVER AT 74TH/YORK,39.826853,-104.949692,North,9,2012,09/21/2012 12:00:00 AM,...,22,29,6,3,2,0,1,0,"(39.82685334, -104.949692)",82.0

In [12]:
#Get list of data columns
list (bike_data_to_load.columns)

['stationId',
 'dataCollected',
 'county',
 'location',
 'lat',
 'long',
 'direction',
 'month',
 'year',
 'dataDate',
 'dayOfWeek',
 'hr00',
 'hr01',
 'hr02',
 'hr03',
 'hr04',
 'hr05',
 'hr06',
 'hr07',
 'hr08',
 'hr09',
 'hr10',
 'hr11',
 'hr12',
 'hr13',
 'hr14',
 'hr15',
 'hr16',
 'hr17',
 'hr18',
 'hr19',
 'hr20',
 'hr21',
 'hr22',
 'hr23',
 'Location 1',
 'Counties']

In [13]:
Bicycle_reduced = bike_data_to_load[['stationId', 'dataCollected', 'county', 'location', 'lat',
'long',
'month',
'year',
'dataDate',
'dayOfWeek', 'hr00',
 'hr01',
 'hr02',
 'hr03',
 'hr04',
 'hr05',
 'hr06',
 'hr07',
 'hr08',
 'hr09',
 'hr10',
 'hr11',
 'hr12',
 'hr13',
 'hr14',
 'hr15',
 'hr16',
 'hr17',
 'hr18',
 'hr19',
 'hr20',
 'hr21',
 'hr22',
 'hr23',
'Location 1']]
Bicycle_reduced.head()

,stationId,dataCollected,county,location,lat,long,month,year,dataDate,dayOfWeek,...,hr15,hr16,hr17,hr18,hr19,hr20,hr21,hr22,hr23,Location 1
0,B9012B,BIKE,Pueblo,"Memorial Dr, Lamar, CO",38.071995,-102.615190,5,2014,05/18/2014 12:00:00 AM,1,...,0,2,2,0,0,0,0,0,0,"(38.071995, -102.61519)"
1,B9012B,BIKE,Pueblo,"Memorial Dr, Lamar, CO",38.071995,-102.615190,10,2013,10/28/2013 12:00:00 AM,2,...,0,1,2,0,0,0,0,0,0,"(38.071995, -102.61519)"
2,B00050,BIKE & PEDESTRIAN,Weld,Greeley (Pouder River Trail at SH 257),40.444467,-104.883688,10,2012,10/25/2012 12:00:00 AM,5,...,3,1,1,0,0,0,0,0,0,"(40.4444673, -104.883688)"
3,B00049,BIKE & PEDESTRIAN,Adams,SOUTH PLATTE RIVER AT 74TH/YORK,39.826853,-104.949692,9,2012,09/29/2012 12:00:00 AM,7,...,17,17,14,4,0,3,1,0,0,"(39.82685334, -104.949692)"
4,B00049,BIKE & PEDESTRIAN,Adams,SOUTH PLATTE RIVER AT 74TH/YORK,39.826853,-104.949692,9,2012,09/21/2012 12:00:00 AM,6,...,18,22,29,6,3,2,0,1,0,"(39.82685334, -104.949692)"

In [14]:
#Drop all rows with missing information
Bicycle_reduced = Bicycle_reduced.dropna(how = "any")

In [15]:
#Verify dropped rows
Bicycle_reduced.count()

stationId        61489
dataCollected    61489
county           61489
location         61489
lat              61489
long             61489
month            61489
year             61489
dataDate         61489
dayOfWeek        61489
hr00             61489
hr01             61489
hr02             61489
hr03             61489
hr04             61489
hr05             61489
hr06             61489
hr07             61489
hr08             61489
hr09             61489
hr10             61489
hr11             61489
hr12             61489
hr13             61489
hr14             61489
hr15             61489
hr16             61489
hr17             61489
hr18             61489
hr19             61489
hr20             61489
hr21             61489
hr22             61489
hr23             61489
Location 1       61489
dtype: int64

In [16]:
#Rename columns
Bicycle_reduced.rename(columns = {"stationId":"Station ID",
                                        "dataCollected" : "Data Collected",
                                        "county" : "County", 
                                        "location" : "Location",
                                        "lat" : "Lat",
                                        "long" : "Long",
                                        "month" : "Month",
                                        "year" : "Year",
                                        "dataDate" : "Data Date",
                                        "dayOfWeek" : "Day of Week",
                                        "hr00" : "Hr00", "hr01" : "Hr01", "hr02" : "Hr02",
                                        "hr03" : "Hr03", "hr04": "Hr04" , "hr05" : "Hr05", "hr06": "Hr06", "hr07" : "Hr07",
                                        "hr08" : "Hr08", "hr09" : "Hr09", "hr10" : "Hr10", "hr11" : "Hr11", "hr12" : "Hr12", "hr13": "Hr13",
                                        "h14" : "Hr14", "hr15" : "Hr15", "hr16" : "Hr16", "hr17" : "Hr17", "hr18" : "Hr18", "hr19" : "Hr19",
                                        "hr20" : "Hr20", "hr21" : "Hr21", "hr22" : "Hr22", "hr23" : "Hr23"}, inplace = True,)
Bicycle_reduced.head()

,Station ID,Data Collected,County,Location,Lat,Long,Month,Year,Data Date,Day of Week,...,Hr15,Hr16,Hr17,Hr18,Hr19,Hr20,Hr21,Hr22,Hr23,Location 1
0,B9012B,BIKE,Pueblo,"Memorial Dr, Lamar, CO",38.071995,-102.615190,5,2014,05/18/2014 12:00:00 AM,1,...,0,2,2,0,0,0,0,0,0,"(38.071995, -102.61519)"
1,B9012B,BIKE,Pueblo,"Memorial Dr, Lamar, CO",38.071995,-102.615190,10,2013,10/28/2013 12:00:00 AM,2,...,0,1,2,0,0,0,0,0,0,"(38.071995, -102.61519)"
2,B00050,BIKE & PEDESTRIAN,Weld,Greeley (Pouder River Trail at SH 257),40.444467,-104.883688,10,2012,10/25/2012 12:00:00 AM,5,...,3,1,1,0,0,0,0,0,0,"(40.4444673, -104.883688)"
3,B00049,BIKE & PEDESTRIAN,Adams,SOUTH PLATTE RIVER AT 74TH/YORK,39.826853,-104.949692,9,2012,09/29/2012 12:00:00 AM,7,...,17,17,14,4,0,3,1,0,0,"(39.82685334, -104.949692)"
4,B00049,BIKE & PEDESTRIAN,Adams,SOUTH PLATTE RIVER AT 74TH/YORK,39.826853,-104.949692,9,2012,09/21/2012 12:00:00 AM,6,...,18,22,29,6,3,2,0,1,0,"(39.82685334, -104.949692)"

In [17]:
# Replace values within Data Collected column
Bicycle_reduced["Data Collected"] = Bicycle_reduced["Data Collected"].replace({'BIKE&PED':'BIKE & PEDESTRIAN', 'PED':'PEDESTRIAN'})

In [18]:
# Verify unique values within Data colected column
Bicycle_reduced["Data Collected"].unique()

array(['BIKE', 'BIKE & PEDESTRIAN', 'PEDESTRIAN'], dtype=object)

In [19]:
#Verify counties
Bicycle_reduced["County"].unique()

array(['Pueblo', 'Weld', 'Adams', 'Denver', 'Jefferson', 'Larimer',
       'Summit', 'Douglas', 'Eagle', 'Boulder', 'Arapahoe', 'Mesa',
       'El Paso', 'La Plata', 'Routt', 'Garfield', 'Broomfield',
       'Montrose', 'Teller', 'Clear Creek'], dtype=object)

In [20]:
#Verify number of years
Bicycle_reduced["Year"].unique()

array([2014, 2013, 2012, 2015, 2011, 2009, 2010], dtype=int64)

In [21]:
Bicycle_reduced.dtypes

Station ID         object
Data Collected     object
County             object
Location           object
Lat               float64
Long              float64
Month               int64
Year                int64
Data Date          object
Day of Week         int64
Hr00                int64
Hr01                int64
Hr02                int64
Hr03                int64
Hr04                int64
Hr05                int64
Hr06                int64
Hr07                int64
Hr08                int64
Hr09                int64
Hr10                int64
Hr11                int64
Hr12                int64
Hr13                int64
hr14                int64
Hr15                int64
Hr16                int64
Hr17                int64
Hr18                int64
Hr19                int64
Hr20                int64
Hr21                int64
Hr22                int64
Hr23                int64
Location 1         object
dtype: object

In [22]:
#Group hours into single days for each county
County_count = Bicycle_reduced[(Bicycle_reduced["Hr00": "Hr23"]).sum()["County"]]
County_count

TypeError: cannot do slice indexing on Int64Index with these indexers [Hr00] of type str